name: Deploy Frontend ReactJS

on:
  push:
    branches:
      - main # Pastikan branch Anda memang 'main'

jobs:
  deploy:
    name: 🎉 Build & Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Mengambil kode terbaru
        uses: actions/checkout@v4 # Sudah diupdate ke v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4 # Sudah diupdate ke v4
        with:
          node-version: "24.13.0"

      - name: 🔨 Install & Build
        run: |
          npm install
          npm run build

      - name: 📂 Upload ke Rumahweb via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/client/ # PENTING: Jika React Anda dibuat pakai Vite, ubah tulisan ./build/ ini menjadi ./dist/
          server-dir: /
          port: 21
          protocol: ftp
          security: loose # perubahan
